#!/bin/bash
# Reproduce the native boundary experiment from a clean checkout: build, bundle, sign, launch the bundle from a fresh
# path with no toolchain on PATH, drive every check that needs no human click, and write receipts under receipts/.
# VARIANT=default (no entitlements) or VARIANT=sandbox (bundle/sandbox/*.entitlements).
set -uo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"
MODE="${1:-}"
VARIANT="${VARIANT:-default}"
OUT="$ROOT/.build"
if [ "$MODE" = "--verify-failure-exit" ]; then R="$OUT/failure-exit-receipt"; else R="$ROOT/receipts/$VARIANT"; fi
STATE="$HOME/Library/Application Support/TakeformProof"
if [ "$VARIANT" = sandbox ]; then
  export PROOF_APP_GROUP=group.com.takeform.proof
  STATE="$HOME/Library/Group Containers/group.com.takeform.proof/TakeformProof"
fi
CTRL="$STATE/control"
rm -rf "$R"
mkdir -p "$R/screens" "$OUT"
: > "$R/checks.txt"
: > "$R/run.log"
FAILURES=0

redact() { sed -E -e "s#$HOME#\$HOME#g"; }
say() { echo "[$(date -u +%H:%M:%S)] $*" | tee -a "$R/run.log" >&2; }
pass() { echo "PASS $*" | tee -a "$R/checks.txt" >&2; }
failc() { FAILURES=$((FAILURES + 1)); echo "FAIL $*" | tee -a "$R/checks.txt" >&2; }
limit() { echo "LIMIT $*" | tee -a "$R/checks.txt" >&2; }
now_ms() { perl -MTime::HiRes=time -e 'printf("%.0f\n", time*1000)'; }
median() { printf '%s\n' "$@" | sort -n | awk '{a[NR]=$1} END { if (NR == 0) print "-"; else if (NR % 2 == 1) print a[(NR+1)/2]; else print (a[NR/2] + a[NR/2+1]) / 2 }'; }
jsonnum() { grep -Eo "\"$1\":-?[0-9.]+" | head -1 | cut -d: -f2; }
jsonnum_all() { grep -Eo "\"$1\":-?[0-9.]+" | cut -d: -f2; }
jsonstr() { grep -o "\"$1\":\"[^\"]*\"" | head -1 | sed 's/^[^:]*:"//; s/"$//'; }
metric() { grep -Eo "\"$1\" : -?[0-9.]+" "$STATE/app-metrics.json" 2>/dev/null | head -1 | awk '{print $3}'; }
wait_metric() { local i=0; while [ $i -lt $(( $2 * 10 )) ]; do grep -q "\"$1\"" "$STATE/app-metrics.json" 2>/dev/null && return 0; sleep 0.1; i=$((i+1)); done; return 1; }
wait_ctrl_gone() { local i=0; while [ $i -lt 50 ] && [ -e "$CTRL/$1" ]; do sleep 0.1; i=$((i+1)); done; }
shot() { touch "$CTRL/shot-$1"; wait_ctrl_gone "shot-$1"; }

if [ "$MODE" = "--verify-failure-exit" ]; then
  failc "injected aggregate exit-status regression"
  [ "$FAILURES" -eq 0 ] && exit 0
  exit 1
fi

if "$ROOT/run-proof.sh" --verify-failure-exit >/dev/null 2>&1; then
  failc "aggregate failure exit-status regression returned zero"
else
  pass "aggregate failure exit-status regression returned nonzero"
fi

say "phase 0 environment"
{
  echo "date: $(date -u +%FT%TZ)"
  sw_vers
  xcodebuild -version
  swift --version 2>&1 | head -1
  sysctl hw.model hw.ncpu hw.memsize machdep.cpu.brand_string
  ffmpeg -version | head -1
  echo "codesigning identities: $(security find-identity -v -p codesigning 2>&1 | tail -1)"
  echo "variant: $VARIANT"
} 2>&1 | redact > "$R/environment.txt"

say "phase 1 build debug and release"
if (cd "$ROOT" && swift build -c debug > "$OUT/build-debug.log" 2>&1); then pass "swift build -c debug"; else failc "swift build -c debug"; fi
{ echo "\$ swift build -c debug"; tail -12 "$OUT/build-debug.log"; } | redact > "$R/build-debug.txt"
if (cd "$ROOT" && swift build -c release > "$OUT/build-release.log" 2>&1); then pass "swift build -c release"; else failc "swift build -c release"; fi
{ echo "\$ swift build -c release"; tail -12 "$OUT/build-release.log"; } | redact > "$R/build-release.txt"

say "phase 2 fixture"
ffmpeg -y -loglevel error -f lavfi -i "testsrc=duration=2:size=320x240:rate=30" -f lavfi -i "sine=frequency=440:duration=2" \
  -c:v libx264 -pix_fmt yuv420p -c:a aac -shortest "$OUT/fixture.mp4"
if [ -s "$OUT/fixture.mp4" ]; then pass "fixture generated by ffmpeg (testsrc plus 440 Hz sine)"; else failc "fixture generated"; fi

say "phase 3 bundle and sign ($VARIANT)"
if RECEIPTS_DIR="$R" "$ROOT/bundle.sh" "$VARIANT" >> "$R/run.log" 2>&1; then pass "bundle.sh assembled and signed inside out"; else failc "bundle.sh"; fi
if grep -q "verify exit 0" "$R/bundle-verify-$VARIANT.txt"; then pass "codesign --verify --deep --strict"; else failc "codesign --verify --deep --strict"; fi
if grep -q "spctl exit 3" "$R/bundle-verify-$VARIANT.txt"; then pass "spctl -a -vv refuses the ad-hoc bundle (expected distribution gap)"; else failc "spctl refusal recorded"; fi

say "phase 4 fresh copy outside the build tree"
FRESH="$(mktemp -d /tmp/takeform-proof.XXXXXX)"
ditto "$OUT/bundle/Takeform Proof.app" "$FRESH/Takeform Proof.app"
APP="$FRESH/Takeform Proof.app"
BIN="$APP/Contents/MacOS"
echo "$FRESH" > "$OUT/fresh-path.txt"
ctl() { "$BIN/proofctl" "$@"; }
run_ctl() {
  local name="$1" out="$2"; shift 2
  ctl "$@" | redact > "$R/$out"
  if grep -q '"pass":true' "$R/$out" && ! grep -q '"pass":false' "$R/$out"; then pass "$name"; else failc "$name (see receipts/$out)"; fi
}
stop_all() {
  pkill -f "Takeform Proof.app/Contents/MacOS/ProofApp" 2>/dev/null
  pkill -f "Takeform Proof.app/Contents/MacOS/ProofService" 2>/dev/null
  pkill -f "Takeform Proof.app/Contents/MacOS/ProofHelper" 2>/dev/null
  sleep 0.4
}
launch_app() {
  env -i HOME="$HOME" USER="$USER" LOGNAME="$USER" TMPDIR="${TMPDIR:-/tmp}" PATH=/usr/bin:/bin:/usr/sbin:/sbin \
    ${PROOF_APP_GROUP:+PROOF_APP_GROUP="$PROOF_APP_GROUP"} \
    PROOF_AUTO=1 PROOF_AUTO_ROLE="${PROOF_AUTO_ROLE:-proposer}" PROOF_DOUBLE_APPROVE=1 PROOF_PAIR_GRANT_DELAY_MS=250 "$@" "$BIN/ProofApp" >> "$OUT/app-stdout.log" 2>&1 &
}

say "phase 5 cold start x3 (app process start to first receipt)"
security delete-generic-password -s com.takeform.proof.cli >/dev/null 2>&1
COLD=(); SPAWN=()
for i in 1 2 3; do
  stop_all
  rm -rf "$STATE"
  launch_app PROOF_FIXTURE="$OUT/fixture.mp4"
  if wait_metric coldStartMs 25; then
    COLD+=("$(metric coldStartMs)"); SPAWN+=("$(metric spawnToSocketMs)")
    pass "cold start $i produced a first receipt"
  else
    COLD+=("timeout"); SPAWN+=("timeout")
    if [ "$VARIANT" = sandbox ]; then limit "sandbox cold start $i produced no receipt"; else failc "cold start $i"; fi
  fi
done
if [ "$VARIANT" = sandbox ] && [ -z "$(metric coldStartMs)" ]; then
  APP_STATE="absent"
  SERVICE_STATE="absent"
  SOCKET_STATE="absent"
  STATE_DIR_STATE="absent"
  pgrep -f "$BIN/ProofApp" >/dev/null && APP_STATE="running"
  pgrep -f "$BIN/ProofService" >/dev/null && SERVICE_STATE="running"
  [ -S "$STATE/proof.sock" ] && SOCKET_STATE="present"
  [ -d "$STATE" ] && STATE_DIR_STATE="present"
  {
    echo "status: measured limit"
    echo "app process after third launch: $APP_STATE"
    echo "expected app-group state directory: $STATE_DIR_STATE"
    echo "service process: $SERVICE_STATE"
    echo "Unix socket: $SOCKET_STATE"
    echo "result: no first receipt became observable within the three bounded observation windows"
    echo "downstream checks: not run because the required app-to-service transport did not exist"
  } > "$R/sandbox-boundary.txt"
  redact < "$STATE/app-metrics.json" > "$R/app-metrics.json"
  limit "sandboxed app-owned service boundary unavailable; downstream commands not run"
  stop_all
  {
    echo "# Measurements, sandbox variant"
    echo
    echo "After the third launch attempt, the app process was $APP_STATE, the expected app-group state directory was $STATE_DIR_STATE, the service process was $SERVICE_STATE and the Unix socket was $SOCKET_STATE. No first receipt appeared in any of the three 25-second observation windows."
    echo "File access, pairing, commands, helper lifecycle and SMAppService were not run because the transport prerequisite failed."
    echo "Signing and entitlement inspection are in codesign-sandbox.txt and bundle-verify-sandbox.txt."
    echo
    sed 's/^/- /' "$R/checks.txt"
  } > "$R/measurements-sandbox.md"
  SLASH="/"
  TILDE="~"
  HYG_PATTERN="${SLASH}Users${SLASH}|${TILDE}${SLASH}|Ko""da|api_""key|token""=|sk""-|ghp""_"
  HYG="$(rg -n "$HYG_PATTERN" "$ROOT" --glob '!.build/**' 2>/dev/null)"
  if [ -z "$HYG" ]; then pass "hygiene scan clean"; else failc "hygiene scan hits"; echo "$HYG" >&2; fi
  say "done at measured sandbox boundary limit"
  [ "$FAILURES" -eq 0 ] && exit 0
  exit 1
fi
if pgrep -f "$BIN/ProofApp" >/dev/null; then pass "bundle launched from $FRESH with PATH=/usr/bin:/bin:/usr/sbin:/sbin"; else failc "bundle launch from fresh path"; fi
grep -Eq 'readOK.*true' "$STATE/app-metrics.json" && pass "service read the creator-granted fixture through the bookmark" || failc "service read of granted fixture"
sleep 0.5
shot 01-launched

say "phase 6 negative tests before pairing"
run_ctl "unauthenticated CLI cannot submit describeFixture" neg-1-unauthenticated.json describe --no-token --expect rejected:unauthenticated
run_ctl "forged payload actor=creator does not elevate an unauthenticated connection" neg-2-forged-actor.json describe --no-token --claim creator --expect rejected:unauthenticated
run_ctl "unauthenticated CLI cannot approve a pairing" neg-3-approve-unauth.json approve nothing --no-token --expect rejected:unauthorized

say "phase 7 pairing x3 (request, app auto-approves as proposer, first authenticated call)"
PAIR=(); FIRST=()
for i in 1 2 3; do
  ctl forget > /dev/null
  run_ctl "pairing $i approved and first authenticated describe succeeded" "pair-$i.json" pair --label "proofctl run $i" --then-describe --expect paired
  PAIR+=("$(jsonnum pairingRequestToApprovalMs < "$R/pair-$i.json")")
  FIRST+=("$(jsonnum approvalToFirstReceiptMs < "$R/pair-$i.json")")
  if grep -q '"role":"proposer"' "$R/pair-$i.json"; then pass "grant $i carries role proposer"; else failc "grant $i role"; fi
  if grep -q '"keychainStoreStatus":0' "$R/pair-$i.json"; then pass "token stored in login Keychain (SecItemAdd status 0)"; else failc "keychain store status"; fi
done
if grep -q 'rejected:pairingAlreadyDecided' "$STATE/app-metrics.json"; then
  pass "a second approval with a different command id cannot mint another session"
else
  failc "second approval was not rejected as pairingAlreadyDecided"
fi
ctl audit-token-absence "$R" > "$R/token-absence.json"
if grep -q '"issuedTokenPresent":"false"' "$R/token-absence.json" && grep -q '"pass":"true"' "$R/token-absence.json"; then
  pass "issued pairing token is absent from CLI stdout and receipts"
else
  failc "issued pairing token leaked to CLI stdout or receipts"
fi
security find-generic-password -s com.takeform.proof.cli 2>&1 | grep -v "^password" | redact > "$R/keychain-item.txt"

ctl forget > /dev/null
if ctl pair --label "forced Keychain failure" --then-describe --expect paired --simulate-keychain-status 100001 > "$R/neg-keychain-store.json"; then
  KEYCHAIN_FAILURE_EXIT=0
else
  KEYCHAIN_FAILURE_EXIT=$?
fi
if [ "$KEYCHAIN_FAILURE_EXIT" -eq 5 ]; then
  pass "approved pairing with Keychain store failure exits 5"
else
  failc "approved pairing with Keychain store failure exited $KEYCHAIN_FAILURE_EXIT instead of 5"
fi
if grep -q '"paired"' "$R/neg-keychain-store.json" && grep -q '"serverExpectationMet":true' "$R/neg-keychain-store.json" && grep -q '"pass":false' "$R/neg-keychain-store.json" && grep -q '"keychainStoreStatus":100001' "$R/neg-keychain-store.json" && grep -q '"localCredentialStored":false' "$R/neg-keychain-store.json" && grep -q 'local authenticated commands are unavailable' "$R/neg-keychain-store.json"; then
  pass "Keychain failure keeps the server approval observable and reports a token-free local credential error"
else
  failc "Keychain failure outcome was not truthful and explicit"
fi
if [ "$(wc -l < "$R/neg-keychain-store.json" | tr -d ' ')" -eq 1 ] && ! grep -q 'describe-after-pair' "$R/neg-keychain-store.json"; then
  pass "Keychain failure does not use the transient grant for an authenticated follow-up"
else
  failc "Keychain failure used the transient grant after local storage failed"
fi
run_ctl "pairing recovered after the focused Keychain failure" keychain-recovery-pair.json pair --label "proofctl recovery" --then-describe --expect paired
shot 02-paired

say "phase 8 warm round trips"
run_ctl "warm describe x5 from paired CLI" warm.json describe --repeat 5 --expect receipt
WARM=($(jsonnum_all roundTripMs < "$R/warm.json"))

say "phase 9 D6 same command, two doors, same command id"
run_ctl "CLI describe with fixed command id" d6-cli-first.json describe --id d6-same-command-id --expect receipt
run_ctl "CLI replay of the same command id" d6-cli-replay.json describe --id d6-same-command-id --expect receipt
A="$(jsonstr issuedAt < "$R/d6-cli-first.json")"; B="$(jsonstr issuedAt < "$R/d6-cli-replay.json")"
if [ -n "$A" ] && [ "$A" = "$B" ]; then pass "replayed command id returned the first receipt (issuedAt $A)"; else failc "replay receipt differs ($A vs $B)"; fi
touch "$CTRL/describe"; wait_ctrl_gone describe; sleep 0.3
ctl receipts describeFixture | redact > "$R/d6-receipts-both-doors.json"
if grep -q '"creator"' "$R/d6-receipts-both-doors.json" && grep -q '"pairedCLI"' "$R/d6-receipts-both-doors.json"; then pass "describeFixture receipts exist from both doors (creator and pairedCLI) with one shape"; else failc "both-door receipts"; fi

say "phase 10 paired CLI cannot use creator-only commands"
run_ctl "paired CLI cannot approve pairing" neg-4-approve.json approve some-request --expect rejected:unauthorized
run_ctl "paired CLI cannot revoke a session" neg-5-revoke.json revoke some-session --expect rejected:unauthorized
run_ctl "paired CLI cannot shut the service down" neg-6-shutdown.json shutdown --expect rejected:unauthorized
run_ctl "paired CLI with forged actor=creator still classified pairedCLI" neg-7-forged-paired.json revoke some-session --claim creator --expect rejected:unauthorized

say "phase 11 helper lease, cancel from CLI x3, stale lease write"
CANCEL=()
for i in 1 2 3; do
  run_ctl "start attempt $i" "attempt-$i-start.json" start 20 --expect receipt
  LEASE="$(grep -o 'attempt [0-9A-Fa-f-]* helper pid [0-9]*' "$R/attempt-$i-start.json" | head -1 | awk '{print $2}')"
  HPID="$(grep -o 'attempt [0-9A-Fa-f-]* helper pid [0-9]*' "$R/attempt-$i-start.json" | head -1 | awk '{print $5}')"
  sleep 1.2
  [ "$i" = 1 ] && shot 03-attempt-running
  run_ctl "write with live lease $i accepted" "attempt-$i-write.json" write "$LEASE" "progress from CLI" --expect receipt
  run_ctl "cancel from CLI $i" "attempt-$i-cancel.json" cancel "$LEASE" --expect receipt
  CANCEL+=("$(grep -o 'SIGTERM to exit [0-9.]*' "$R/attempt-$i-cancel.json" | head -1 | awk '{print $4}')")
  run_ctl "stale lease write $i rejected" "attempt-$i-stale-write.json" write "$LEASE" "late write" --expect rejected:staleLease
  sleep 0.2
  if [ -z "$HPID" ]; then failc "helper pid missing after start"; elif kill -0 "$HPID" 2>/dev/null; then failc "helper $HPID still alive after cancel"; else pass "helper $HPID exited after cancel"; fi
done
run_ctl "start attempt for app cancel" attempt-app-start.json start 20 --expect receipt
sleep 0.8; touch "$CTRL/cancel-current"; wait_ctrl_gone cancel-current; sleep 0.5
if grep -q '"state" : "cancelled"' "$STATE/attempts.json"; then pass "cancel from the app"; else failc "cancel from the app"; fi
shot 04-cancelled

say "phase 12 kill service mid-attempt x3, relaunch, reconcile"
RELAUNCH=(); RECON=()
for i in 1 2 3; do
  run_ctl "start attempt for kill $i" "kill-$i-start.json" start 30 --expect receipt
  HPID="$(grep -o 'helper pid [0-9]*' "$R/kill-$i-start.json" | head -1 | awk '{print $3}')"
  SPID="$(grep -o '"servicePid":[0-9]*' "$R/kill-$i-start.json" | head -1 | cut -d: -f2)"
  sleep 0.5
  T0="$(now_ms)"; kill -9 "$SPID"
  ctl wait-socket 15 > "$R/kill-$i-wait.json"; T1="$(now_ms)"
  RELAUNCH+=("$((T1 - T0))")
  sleep 0.6
  if [ "$(grep -c 'interrupted-helper-alive-same-start-time' "$STATE/attempts.json")" -ge "$i" ]; then pass "reconcile $i classified the attempt interrupted by lease plus start time and signalled the orphan helper"; else failc "reconcile $i classification"; fi
  if kill -0 "$HPID" 2>/dev/null; then failc "orphan helper $HPID still alive after reconcile"; else pass "orphan helper $HPID stopped after reconcile"; fi
  RECON+=("$(grep -o '"msSinceServiceProcessStart" : [0-9.]*' "$STATE/attempts.json" | tail -1 | awk '{print $3}')")
done
redact < "$STATE/attempts.json" > "$R/attempts-verified-handshakes.json"
if [ "$(grep -c '"handshake"' "$R/attempts-verified-handshakes.json")" -ge 3 ]; then
  pass "three reconciled helpers had verified lease, pid and start-time handshakes"
else
  failc "verified helper handshakes missing from reconcile evidence"
fi

say "phase 13 pid reuse negative"
touch "$CTRL/quit"; sleep 1
pkill -f "Takeform Proof.app/Contents/MacOS/ProofService"; sleep 0.5
sleep 300 & DECOY=$!
ctl inject-stale-attempt "$DECOY" | redact > "$R/pid-reuse-inject.json"
launch_app
ctl wait-socket 15 > /dev/null; sleep 0.6
if grep -q 'interrupted-pid-reused-start-time-mismatch' "$STATE/attempts.json"; then pass "reconcile classified the reused pid by start-time mismatch"; else failc "pid reuse classification"; fi
if [ "$(grep -o '"signalled" : [a-z]*' "$STATE/attempts.json" | tail -1)" = '"signalled" : false' ]; then pass "reconcile did not signal the reused pid"; else failc "reconcile signalled flag"; fi
if kill -0 "$DECOY" 2>/dev/null; then pass "process reusing the recorded pid is still alive (not signalled)"; else failc "decoy process was killed"; fi
kill "$DECOY" 2>/dev/null

say "phase 14 revocation from the app"
touch "$CTRL/revoke-all"; wait_ctrl_gone revoke-all; sleep 0.3
run_ctl "revoked session fails with revokedSession" neg-8-revoked.json describe --expect rejected:revokedSession
shot 05-revoked

say "phase 15 SMAppService launch agent (D1 alternative)"
touch "$CTRL/quit"; sleep 1
launch_app PROOF_REGISTER_AGENT=1
wait_metric agent 10; sleep 0.5
{ echo "\$ app-metrics agent (register)"; grep -A7 '"agent"' "$STATE/app-metrics.json"; echo; echo "\$ launchctl print gui/$(id -u)/com.takeform.proof.agent"; launchctl print "gui/$(id -u)/com.takeform.proof.agent" 2>&1 | head -30; } | redact > "$R/smappservice.txt"
touch "$CTRL/quit"; sleep 1
pkill -f "Takeform Proof.app/Contents/MacOS/ProofService"; sleep 0.5
{ echo; echo "\$ launchctl kickstart gui/$(id -u)/com.takeform.proof.agent"; launchctl kickstart "gui/$(id -u)/com.takeform.proof.agent" 2>&1; } | redact >> "$R/smappservice.txt"
AGENT_ANSWERED=0
if ctl wait-socket 5 > "$R/smappservice-wait.json" && grep -q '"connected":"true"' "$R/smappservice-wait.json"; then
  AGENT_ANSWERED=1
  pass "launch agent registered through SMAppService answers on the socket"
  ctl status --no-token --expect rejected:unauthenticated | redact > "$R/smappservice-status.json"
  launch_app
  wait_metric coldStartMs 5; sleep 0.3
  if grep -q '"matchesAppRequirement" : true' "$STATE/app-metrics.json"; then pass "app authenticated to the launch-agent service by code requirement"; else failc "app authentication to launch-agent service"; fi
  touch "$CTRL/quit"; sleep 1
  { echo; echo "\$ ps (agent-run service)"; ps -o pid,ppid,command -p "$(pgrep -f 'Contents/MacOS/ProofService' | head -1)"; } | redact >> "$R/smappservice.txt"
else
  say "launch agent did not answer; collecting launchd failure state"
fi
{ echo; echo "\$ launchctl print after kickstart"; launchctl print "gui/$(id -u)/com.takeform.proof.agent" 2>&1 | head -80; } | redact >> "$R/smappservice.txt"
if grep -q 'last exit reason = OS_REASON_CODESIGNING' "$R/smappservice.txt"; then
  pass "SMAppService registered, but launchd rejected the ad-hoc nested service with OS_REASON_CODESIGNING"
elif [ "$AGENT_ANSWERED" = 0 ]; then
  failc "launch agent service did not answer and launchd gave no classified signing reason"
fi
pkill -f "Takeform Proof.app/Contents/MacOS/ProofService"; sleep 0.3
launch_app PROOF_UNREGISTER_AGENT=1
sleep 2
{ echo; echo "\$ app-metrics agent (unregister)"; grep -A7 '"agent"' "$STATE/app-metrics.json"; } | redact >> "$R/smappservice.txt"
touch "$CTRL/quit"; sleep 1
stop_all

say "phase 16 collect receipts"
redact < "$STATE/app-metrics.json" > "$R/app-metrics.json"
redact < "$STATE/service.log" > "$R/service.log"
sed -e '/"bookmark" :/d' "$STATE/service-state.json" | redact > "$R/service-state.json"
redact < "$STATE/attempts.json" > "$R/attempts.json"
cp "$STATE"/screens/*.png "$R/screens/" 2>/dev/null
ctl audit-token-absence "$R" > "$R/token-absence-final.json"
if grep -q '"issuedTokenPresent":"false"' "$R/token-absence-final.json" && grep -q '"pass":"true"' "$R/token-absence-final.json"; then
  pass "issued pairing token is absent from the complete final receipt set"
else
  failc "issued pairing token leaked into the complete final receipt set"
fi
BUNDLE_KB="$(grep -A1 'du -sk' "$R/bundle-verify-$VARIANT.txt" | tail -1 | awk '{print $1}')"
{
  echo "# Measurements, $VARIANT variant"
  echo
  echo "Generated by run-proof.sh on $(date -u +%FT%TZ). Environment in environment.txt. Medians of three unless stated; raw values listed."
  echo
  echo "| Metric | Raw values (ms) | Median (ms) |"
  echo "|---|---|---|"
  echo "| Service cold start, app process start to first receipt (includes service spawn, bookmark grant, describe) | ${COLD[*]} | $(median "${COLD[@]}") |"
  echo "| Service spawn to socket accepting (app observed) | ${SPAWN[*]} | $(median "${SPAWN[@]}") |"
  echo "| Warm describeFixture round trip, paired CLI, 5 runs | ${WARM[*]-} | $(median "${WARM[@]-}") |"
  echo "| Pairing request to approval, service clock, app auto-approve on a 200 ms status poll | ${PAIR[*]} | $(median "${PAIR[@]}") |"
  echo "| Approval to first authenticated receipt, service clock | ${FIRST[*]} | $(median "${FIRST[@]}") |"
  echo "| Cancel SIGTERM to helper exit, service observed | ${CANCEL[*]} | $(median "${CANCEL[@]}") |"
  echo "| Service kill -9 to socket back, CLI observed wall clock (includes the app 200 ms poll) | ${RELAUNCH[*]} | $(median "${RELAUNCH[@]}") |"
  echo "| Relaunched service process start to reconcile done | ${RECON[*]} | $(median "${RECON[@]}") |"
  echo "| Bundle size (KB, du -sk) | $BUNDLE_KB | |"
  echo
  echo "## Checks"
  echo
  sed 's/^/- /' "$R/checks.txt"
} > "$R/measurements-$VARIANT.md"

say "phase 17 hygiene scan over proofs/"
SLASH="/"
TILDE="~"
HYG_PATTERN="${SLASH}Users${SLASH}|${TILDE}${SLASH}|Ko""da|api_""key|token""=|sk""-|ghp""_"
HYG="$(rg -n "$HYG_PATTERN" "$ROOT" --glob '!.build/**' 2>/dev/null)"
if [ -z "$HYG" ]; then pass "hygiene scan clean"; else failc "hygiene scan hits"; echo "$HYG" >&2; fi
say "done. $(grep -c '^PASS' "$R/checks.txt") PASS, $(grep -c '^FAIL' "$R/checks.txt") FAIL. fresh bundle at $FRESH"
[ "$FAILURES" -eq 0 ] && exit 0
exit 1
